id: map_provider_op

uri: file:///home/usanz/zs_t3/t3_ws/src/swarm_obj_finder/zenoh-flow_nodes/map_provider_source.py

configuration:
  common_cfg_file: "{{ BASE_DIR_PATH }}/config/common_cfg.yaml"
  map_yaml_file: "/home/usanz/zs_t3/t3_ws/src/swarm_obj_finder/maps/turtlebot3_world/turtlebot3_world.yaml"
  
outputs: [Map]
tags: []
