id: map_divider_op

uri: file:///home/usanz/zs_t3/t3_ws/src/swarm_obj_finder/zenoh-flow_nodes/map_divider_op.py

configuration:
  common_cfg_file: "/home/usanz/zs_t3/t3_ws/src/swarm_obj_finder/config/common_cfg.yaml"

inputs: [Map]
outputs: [Markers, Divisions, DebugImage]
tags: []
