id: paths_planner_op

uri: file:///home/usanz/zs_t3/t3_ws/src/swarm_obj_finder/zenoh-flow_nodes/paths_planner_op.py

configuration:
  common_cfg_file: "/home/usanz/zs_t3/t3_ws/src/swarm_obj_finder/config/common_cfg.yaml"
  waypoint_separation: 30

inputs: [Map, Divisions]
outputs: [Paths]
tags: []
